
# ========= Border =========
file_panel_border = '#F6F4F2'
sidebar_border = '#F6F4F2'
footer_border = '#F6F4F2'

# ========= Border Active =========
file_panel_border_active = '#a8a8ae'
sidebar_border_active = '#a8a8ae'
footer_border_active = '#a8a8ae'
modal_border_active = '#a8a8ae'

# ========= Background (bg) =========
full_screen_bg = '#110D0C'
file_panel_bg = '#110D0C'
sidebar_bg = '#110D0C'
footer_bg = '#110D0C'
modal_bg = '#110D0C'

# ========= Foreground (fg) =========
full_screen_fg = '#ffffff'
file_panel_fg = '#ffffff'
sidebar_fg = '#ffffff'
footer_fg = '#ffffff'
modal_fg = '#ffffff'

# ========= Special Color =========
cursor = '#ffffff'
correct = '#98a09b'
error = '#ab7c7c'
hint = '#b8bdbc'
cancel = '#ab7c7c'
gradient_color = ['#110D0C', "#8c7b76"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#110D0C'
file_panel_top_path = '#8c7b76'
file_panel_item_selected_fg = '#8c7b76'
file_panel_item_selected_bg = '#110D0C'

# ========= Sidebar Special Items =========
sidebar_title = '#ffffff'
sidebar_item_selected_fg = '#8c7b76'
sidebar_item_selected_bg = '#110D0C'
sidebar_divider = '#F6F4F2'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#ab7c7c'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#98a09b'
