[colors]
[colors.primary]
background = "#110D0C"
foreground = "#ffffff"

[colors.normal]
black   = "#110D0C"
red     = "#ab7c7c"
green   = "#98a09b"
yellow  = "#D3C4B8"
blue    = "#a8a8ae"
magenta = "#b6afb5"
cyan    = "#b8bdbc"
white   = "#F6F4F2"

[colors.bright]
black   = "#8c7b76"
red     = "#d0b3b3"
green   = "#c8ccc9"
yellow  = "#f6f3f0"
blue    = "#d7d7da"
magenta = "#e2dfe2"
cyan    = "#e7e9e9"
white   = "#ffffff"

[colors.cursor]
text   = "#110D0C"
cursor = "#ffffff"
